mod about;
mod editorial;
mod home;
mod navbar;
mod projects;
pub mod resume;
pub use about::AboutPage;
pub use editorial::Footer;
pub use home::HomePage;
pub use navbar::NavBar;
pub use projects::{ProjectDetailPage, ProjectsPage};
pub use resume::Resume;
